ProjekatBanka/ProjekatBanka/Models/Banka.cs
using System.ComponentModel.DataAnnotations;

namespace ProjekatBanka.Models
{
    public class Banka
    {
        [Key]
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Kontakt { get; set; }
        public int Pib { get; set; }

        public ICollection<Filijala> Filijals { get; set; }
    }
}

ProjekatBanka/ProjekatBanka/Models/ErrorViewModel.cs
namespace ProjekatBanka.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjekatBanka/ProjekatBanka/Models/Filijala.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ProjekatBanka.Models
{
    public class Filijala
    {

        [Key]
        public int Id { get; set; }
        public string Adresa { get; set; }
        public int BrojPultova { get; set; }

        [ForeignKey("Banka")]

        public int? BankaId { get; set; }
        public Banka Banka { get; set; }

        public ICollection<Usluga> Uslugas { get; set; }

    }
}

ProjekatBanka/ProjekatBanka/Models/Korisnik.cs
using System.ComponentModel.DataAnnotations;

namespace ProjekatBanka.Models
{
    public class Korisnik
    {
        [Key]
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }

        public string MaticniBroj { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public string Email { get; set; }

        public ICollection<Usluga> Uslugas { get; set; }
    }
}

ProjekatBanka/ProjekatBanka/Models/Usluga.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ProjekatBanka.Models
{
    public class Usluga
    {

        [Key]
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string OpisUsluge { get; set; }
        public string Provizija { get; set; }

        [ForeignKey("Korisnik")]
        public int KorisnikId { get; set; }

        public Korisnik Korisnik { get; set; }

        [ForeignKey("Filijala")]
        public int FilijalaId { get; set; }
        public Filijala Filijala { get; set; }
    }
    

}

ProjekatBanka/ProjekatBanka/Models/ViewModels/AddFilijalaRequest.cs
namespace ProjekatBanka.Models.ViewModels
{
    public class AddFilijalaRequest
    {
        public string Adresa { get; set; }
        public int BrojPultova { get; set; }

        public int BankaId { get; set; }
    }
}

ProjekatBanka/ProjekatBanka/Models/ViewModels/KorisnikRegister.cs
namespace ProjekatBanka.Models.ViewModels
{
    public class KorisnikRegister
    {
        public string Ime { get; set; }
        public string Prezime { get; set; }

        public string MaticniBroj { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public string Email { get; set; }
    }
}

ProjekatBanka/ProjekatBanka/Models/ViewModels/Login.cs
namespace ProjekatBanka.Models.ViewModels
{
    public class Login
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

ProjekatBanka/ProjekatBanka/Models/ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;

namespace ProjekatBanka.Models.ViewModels
{
    public class Register
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage ="Password and confirmation password did not match")]
        public string ConfirmPassword { get; set; }
    }
}

ProjekatBanka/ProjekatBanka/Controllers/BankaController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjekatBanka.Controllers
{
    public class BankaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProjekatBanka/ProjekatBanka/Controllers/FilijalaController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjekatBanka.Controllers
{
    public class FilijalaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProjekatBanka/ProjekatBanka/Controllers/GradController.cs
using Microsoft.AspNetCore.Mvc;
using ProjekatBanka.Data;
using ProjekatBanka.Models;
using ProjekatBanka.Models.ViewModels;

namespace ProjekatBanka.Controllers
{
    public class GradController : Controller
    {
        private readonly BankaDbContext bankaDbContext;
        public GradController(BankaDbContext bankaDbContext)
        {
               this.bankaDbContext = bankaDbContext;
        }
        [HttpGet]
        public IActionResult Add(AddFilijalaRequest addFilijalaRequest)
        {
        
            return View();
        }
        [HttpPost]
        [ActionName("Add")]
        public IActionResult SubmitTag(AddFilijalaRequest addFilijala)
        {
            var filijala = new Filijala()
            {
                BankaId=addFilijala.BankaId,
                Adresa = addFilijala.Adresa,
                BrojPultova = addFilijala.BrojPultova,
            };
            bankaDbContext.Filijalas.Add(filijala);
            bankaDbContext.SaveChanges();
            return View("Add");
        }


    }
}

ProjekatBanka/ProjekatBanka/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjekatBanka.Models;
using System.Diagnostics;

namespace ProjekatBanka.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjekatBanka/ProjekatBanka/Controllers/KorisnikController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjekatBanka.Data;
using ProjekatBanka.Models;

namespace ProjekatBanka.Controllers
{
    public class KorisnikController : Controller
    {
        private readonly BankaDbContext dbContext;
        public KorisnikController(BankaDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        

        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var korisnici = await dbContext.Korisniks.ToListAsync();
            return View(korisnici);
        }
    }


}

ProjekatBanka/ProjekatBanka/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using ProjekatBanka.Data;
using ProjekatBanka.Models.ViewModels;
using ProjekatBanka.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace ProjekatBanka.Controllers
{
    public class RegisterController : Controller
    {
        private readonly BankaDbContext bankaDbContext;
        public RegisterController(BankaDbContext bankaDbContext)
        {
            this.bankaDbContext = bankaDbContext;
        }

        [HttpGet]
        public IActionResult RegisterUser(KorisnikRegister registerKor)
        {
            return View();
        }


        [HttpPost]
        [ActionName("RegisterUser")]
        public IActionResult Register(KorisnikRegister registerKor)
        {

            {
                var korisnik = new Korisnik
                {
                    Ime = registerKor.Ime,
                    Prezime = registerKor.Prezime,
                    MaticniBroj = registerKor.MaticniBroj,
                    Username = registerKor.Username,
                    Password = registerKor.Password,
                    Email = registerKor.Email,
                };

                bankaDbContext.Korisniks.Add(korisnik);
                bankaDbContext.SaveChanges();
                return RedirectToAction("Login");


            }

        }

        public IActionResult Login(Login logovan)
        {
            if(ModelState.IsValid)
            {
             var user = bankaDbContext.Korisniks.FirstOrDefault(u=> u.Username== logovan.Username);
                if(user!=null && user.Password==logovan.Password) 
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }
    }
}

ProjekatBanka/ProjekatBanka/Views/Grad/Add.cshtml
@model ProjekatBanka.Models.ViewModels.AddFilijalaRequest
@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1> Add New Tag - Gradovi Funkcionalnost</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">

        <div class="mb-3">
            <label class="form-label">Banka Id</label>
            <input type="number" class="form-control" asp-for="BankaId" />
        </div>

        <div class="mb-3">
            <label class="form-label">Adresa Filijale</label>
            <input type="text" class="form-control" asp-for="Adresa"/>
        </div>

        <div class="mb-3">
            <label class="form-label">Broj Pultova</label>
            <input type="number" class="form-control" asp-for="BrojPultova"/>
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>

ProjekatBanka/ProjekatBanka/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/carousel/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#">Banka</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Korisnik" asp-action="Index">Korisnici</a>
                    </li>
                    <li class="nav-item dropdown">
                        <button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            Gradovi
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            <li>
                                <a class="dropdown-item" asp-area=""
                                   asp-controller="Grad"
                                   asp-action="Add">
                                    Beograd
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" asp-area=""
                                   asp-controller="Grad"
                                   asp-action="Add">
                                   Novi Sad
                                   </a>
                            </li>
                            <li>
                                <a class="dropdown-item" asp-area=""
                                   asp-controller="Grad"
                                   asp-action="Add">
                                   Nis
                               </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="form-inline mt-2 mt-md-0">
                    <a class="btn btn-outline-success my-2 my-sm-0"  role="button"
                    asp-area="" 
                    asp-controller="Register"
                    asp-action="RegisterUser" type="submit">Sign Up
                       
                    </a>
                </ul>

              

            </div>
        </nav>
    </header>

    <main role="main">

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
                    <div class="container">
                        <div class="carousel-caption text-left">
                            <h1>Example headline.</h1>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>Another example headline.</h1>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
                    <div class="container">
                        <div class="carousel-caption text-right">
                            <h1>One more for good measure.</h1>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>


        <!-- Marketing messaging and featurettes
        ================================================== -->
        <!-- Wrap the rest of the page in another container to center all the content. -->

        <div class="container marketing">

            <!-- Three columns of text below the carousel -->
            <div class="row">
                <div class="col-lg-4">
                    <img class="rounded-circle" src="" alt="Generic placeholder image" width="140" height="140">
                    <h2>Beograd</h2>
                    <p>U Beogradu, kao našem najvećem i glavnom gradu, postoji 20 filijala naše banke.</p>
                    <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                    <h2>Novi Sad</h2>
                    <p>U Novom Sadu postoji 17 filijala.</p>
                    <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                    <h2>Niš</h2>
                    <p>U Nišu se trenutno nalazi 7 filijala naše banke.</p>
                    <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
            </div><!-- /.row -->
            <!-- START THE FEATURETTES -->

            <hr class="featurette-divider">


            <div class="row featurette">
                <div class="col-md-7">
                    <h2 class="featurette-heading">Komercijalna banka <span class="text-muted">Meni najbliža!</span></h2>
                    <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
                </div>
                <div class="col-md-5">
                    <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
                </div>
            </div>

            <hr class="featurette-divider">

            <!-- /END THE FEATURETTES -->

        </div><!-- /.container -->
        <!-- FOOTER -->

    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
</body>
</html>