BankaProjekat/BankaProjekat/Models/Korisnik.cs
using System.ComponentModel.DataAnnotations;

namespace BankaProjekat.Models
{
    public class Korisnik
    {
        [Key]
        public int Id { get; set; }
        public string? Ime { get; set; }
        public string? Prezime { get; set; }

        public string? MaticniBroj { get; set; }

        public string? Username { get; set; }

        public string? Password { get; set; }

        public string? Email { get; set; }

        public ICollection<Usluga> Uslugas { get; set; }
    }
}

BankaProjekat/BankaProjekat/Controllers/KorisnikController.cs
using BankaProjekat.Data;
using BankaProjekat.Models;
using BankaProjekat.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Metadata.Ecma335;

namespace BankaProjekat.Controllers
{
    public class KorisnikController : Controller
    {
        private readonly BankaDbContext bankaDbContext;
        private int id;

        public KorisnikController(BankaDbContext bankaDbContext)
        {
            this.bankaDbContext = bankaDbContext;
        }



        [HttpGet]
        public async Task<IActionResult> Index()
        {

            var korisnici = await bankaDbContext.Korisniks.ToListAsync();
            return View(korisnici);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
            public async Task<IActionResult> Add(AddKorisnik newKorisnik) 
        {
            var employee = new Korisnik()
            {
                Ime = newKorisnik.Ime,
                Prezime = newKorisnik.Prezime,
                MaticniBroj = newKorisnik.MaticniBroj,
                Email = newKorisnik.Email,
                Username = newKorisnik.Username,
                Password = newKorisnik.Password
            };
            await bankaDbContext.Korisniks.AddAsync(employee);
            await bankaDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var korisnik = bankaDbContext.Korisniks.FirstOrDefault(x => x.Id == id);

            if (korisnik != null)
            {
                var viewModel = new UpdateKorisnik()
                {
                    Id = korisnik.Id,
                    Ime = korisnik.Ime,
                    Prezime = korisnik.Prezime,
                    MaticniBroj = korisnik.MaticniBroj,
                    Email = korisnik.Email,
                    Username = korisnik.Username,
                    Password = korisnik.Password
                };
                return View(viewModel);
            }
            
            return RedirectToAction("Index");  
        }

        [HttpPost]
        public async Task<IActionResult> Update (UpdateKorisnik model)
        {
            var korisnik = await bankaDbContext.Korisniks.FindAsync(model.Id);

            if (korisnik != null)

            {
                korisnik.Ime = model.Ime;
                korisnik.Prezime = model.Prezime;
                korisnik.MaticniBroj= model.MaticniBroj;
                korisnik.Email = model.Email;
                korisnik.Username = model.Username;
                korisnik.Password = model.Password;

                await bankaDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
            
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateKorisnik model)
        {
            var korisnik = await bankaDbContext.Korisniks.FindAsync(model.Id);
             if(korisnik != null)
            {
                bankaDbContext.Korisniks.Remove(korisnik);
                await bankaDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }
}

BankaProjekat/BankaProjekat/Views/Korisnik/Add.cshtml
@model BankaProjekat.Models.ViewModels.AddKorisnik
@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1> Add New Tag - Gradovi Funkcionalnost</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">

        <div class="mb-3">
            <label class="form-label">Ime</label>
            <input type="text" class="form-control" asp-for="Ime" />
        </div>

        <div class="mb-3">
            <label class="form-label">Prezime</label>
            <input type="text" class="form-control" asp-for="Prezime" />
        </div>

        <div class="mb-3">
            <label class="form-label">Maticni broj</label>
            <input type="text" class="form-control" asp-for="MaticniBroj" />
        </div>

        <div class="mb-3">
            <label class="form-label">Email</label>
            <input type="text" class="form-control" asp-for="Email" />
        </div>

        <div class="mb-3">
            <label class="form-label">Username</label>
            <input type="text" class="form-control" asp-for="Username" />
        </div>

        <div class="mb-3">
            <label class="form-label">Password</label>
            <input type="text" class="form-control" asp-for="Password" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Add</button>
        </div>
    </form>
</div>

BankaProjekat/BankaProjekat/Views/Korisnik/Index.cshtml
@model List<BankaProjekat.Models.Korisnik>
@{
}
       
<h1>Korisnici</h1>



<table class="table">
    
    
        
    

    <thead>
        <tr>
            <th>Id</th>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Maticni Broj</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var korisnik in Model)
        {
            <tr>
                <td>@korisnik.Id </td>
                <td>@korisnik.Ime </td>
                <td>@korisnik.Prezime </td>
                <td>@korisnik.MaticniBroj </td>
                <td><a href="Update/@korisnik.Id">Update</a></td>
            </tr>
        }
    </tbody>
    
</table>

<ul class="form-inline mt-2 mt-md-0">
    <a class="btn btn-outline-success my-2 my-sm-0" role="button"
       asp-area=""
       asp-controller="Korisnik"
       asp-action="Add" type="submit">
        Add

    </a>
</ul>

BankaProjekat/BankaProjekat/Views/Korisnik/Update.cshtml
@model BankaProjekat.Models.ViewModels.UpdateKorisnik
@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1> Edit Korisnik</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post" action="Edit">

        <div class="mb-3">
            <label class="form-label">Id</label>
            <input type="text" class="form-control" asp-for="Id" readonly>
        </div>

        <div class="mb-3">
            <label class="form-label">Ime</label>
            <input type="text" class="form-control" asp-for="Ime" />
        </div>

        <div class="mb-3">
            <label class="form-label">Prezime</label>
            <input type="text" class="form-control" asp-for="Prezime" />
        </div>

        <div class="mb-3">
            <label class="form-label">Maticni broj</label>
            <input type="text" class="form-control" asp-for="MaticniBroj" />
        </div>

        <div class="mb-3">
            <label class="form-label">Email</label>
            <input type="text" class="form-control" asp-for="Email" />
        </div>

        <div class="mb-3">
            <label class="form-label">Username</label>
            <input type="text" class="form-control" asp-for="Username" />
        </div>

        <div class="mb-3">
            <label class="form-label">Password</label>
            <input type="text" class="form-control" asp-for="Password" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Update</button>
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-dark"
                    asp-action="Delete"
                    asp-controller="Korisnik">
                Delete
            </button>
        </div>
    </form>
</div>